<?php

namespace MYT\MakeYourTeamBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends EntityRepository
{

    public function getAnnonceByCategorie(array $catagories)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->join('a.categorie', 'c')->addSelect('c');
        $qb->where($qb->expr()->in('c.nom', $catagories));

        return $qb->getQuery()->getResult();
    }

    public function getPublishedAnnonces()
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM MakeYourTeamBundle:Annonce a WHERE a.published = true'
            );


        return $query->getResult();
    }

    public function getAnnonceBySlug($slug)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM MakeYourTeamBundle:Annonce a WHERE a.slug = :slug'
            )->setParameter('slug', $slug);


        return $query->getFirstResult();
    }

    public function getList($page=1, $maxperpage=1)
    {
        $qb = $this->_em->createQueryBuilder()
            ->select('a')
            ->from('MakeYourTeamBundle:Annonce','a')
        ;

        $qb->setFirstResult(($page-1) * $maxperpage)
            ->setMaxResults($maxperpage);

        return new Paginator($qb);
    }

    public function countPublishedTotal()
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(a) FROM MakeYourTeamBundle:Annonce a WHERE a.published = true'
            );

        return $query->getOneOrNullResult();
    }


//    public function getPublishedQueryBuilder()
//    {
//        return $this->createQueryBuilder('a')
//            ->where('a.published = :published')
//            ->setParameter('published', true)
//            ;
//    }

    //Ajouter dans un XxxType
//    $builder->add('advert', 'entity', array(
//    'class'         => 'MakeYourTeamBundle:Annonce',
//    'property'      => 'title',
//    'query_builder' => function(AnnonceRepository $repo) {
//        return $repo->getPublishedQueryBuilder();
//}

}
