<?php

namespace MYT\MakeYourTeamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnonceCompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceCompetenceRepository extends EntityRepository
{
}
