<?php

namespace MYT\MakeYourTeamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends EntityRepository
{

    public function getAnnonceByCategorie(array $catagories)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->join('a.categorie', 'c')->addSelect('c');
        $qb->where($qb->expr()->in('c.nom', $catagories));

        return $qb->getQuery()->getResult();
    }


//    public function getPublishedQueryBuilder()
//    {
//        return $this->createQueryBuilder('a')
//            ->where('a.published = :published')
//            ->setParameter('published', true)
//            ;
//    }

    //Ajouter dans un XxxType
//    $builder->add('advert', 'entity', array(
//    'class'         => 'MakeYourTeamBundle:Annonce',
//    'property'      => 'title',
//    'query_builder' => function(AnnonceRepository $repo) {
//        return $repo->getPublishedQueryBuilder();
//}

}
