<?php

namespace MYT\MakeYourTeamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnonceCompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyUserCompetenceRepository extends EntityRepository
{

    public function deleteByUser($user)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'DELETE FROM MakeYourTeamBundle:MyUserCompetence u WHERE u.user = :myuser'
            )->setParameter('myuser', $user);
        $query->execute();
    }

}
