services:
    make_your_team.registration.form.type:
        class: MYT\UserBundle\Form\Type\RegistrationFormType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: myt_user_registration }

    make_your_team.profile.form.type:
        class: MYT\UserBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: myt_user_profile }